"""
build_dashboard_data.py
=======================
Recomputes the held-out test predictions (same seed, same split -> identical
rows) and emits a dense threshold grid so the dashboard can move the operating
point in real time without shipping 39k probabilities to the browser.

For every threshold t in [0.01, 0.99] we precompute the full confusion matrix.
99 rows of six integers is 2 KB. Shipping the raw probabilities would be 300 KB
and force the browser to re-sort on every slider tick.
"""

import json
import warnings

import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from src import campaign, classify
from src import config as C

warnings.filterwarnings("ignore")

M = json.load(open(C.OUT_DIR / "metrics.json"))
df = pd.read_pickle(C.DATA_DIR / "_ckpt_df.pkl")

Xc, yc, feats = classify.build_churn_matrix(df)
Xtr, Xte, ytr, yte = train_test_split(
    Xc, yc, test_size=C.TEST_SIZE, random_state=C.RANDOM_STATE, stratify=yc
)
model = joblib.load(C.MODEL_DIR / "churn_model.joblib")
proba = model.predict_proba(Xte)[:, 1]
y = yte.to_numpy()

# Revenue attached to each held-out customer, for the budget calculator.
rev = df.loc[Xte.index, "average_revenue"].to_numpy()

grid = []
for t in np.arange(0.01, 1.00, 0.01):
    pred = proba >= t
    tp = int((pred & (y == 1)).sum())
    fp = int((pred & (y == 0)).sum())
    fn = int((~pred & (y == 1)).sum())
    tn = int((~pred & (y == 0)).sum())
    prec = tp / (tp + fp) if (tp + fp) else 0.0
    rec = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * prec * rec / (prec + rec) if (prec + rec) else 0.0
    grid.append(
        {
            "t": round(float(t), 2),
            "tp": tp, "fp": fp, "fn": fn, "tn": tn,
            "precision": round(prec, 4),
            "recall": round(rec, 4),
            "f1": round(f1, 4),
            "accuracy": round((tp + tn) / len(y), 4),
            "specificity": round(tn / (tn + fp), 4) if (tn + fp) else 0.0,
            "contacted": int(pred.sum()),
            # Revenue sitting behind correctly-flagged churners: the ceiling on
            # what a perfect retention campaign could save at this threshold.
            "rev_saved_ceiling": round(float(rev[pred & (y == 1)].sum()), 0),
            # Revenue spent contacting people who were never going to leave.
            "rev_wasted": round(float(rev[pred & (y == 0)].sum()), 0),
        }
    )

payload = {
    "headline": {
        "raw_rows": M["raw_rows"],
        "clean_rows": M["clean_rows"],
        "dropped_aon": M["cleaning_report"]["dropped_by_aon_filter"],
        "churn_base_rate": M["churn_base_rate"],
        "n_segments": M["chosen_k"],
        "roc_auc": M["churn_metrics_tuned"]["roc_auc"],
        "pr_auc": M["churn_metrics_tuned"]["pr_auc"],
        "total_revenue": M["total_monthly_revenue"],
        "revenue_at_risk": M["total_revenue_at_risk"],
        "best_model": M["churn_best_model"],
        "tuned_threshold": M["churn_threshold"],
        "runtime": M["runtime_seconds"],
        "utg": M["utg_count"],
        "ucg": M["ucg_count"],
        "test_positives": int((y == 1).sum()),
        "test_negatives": int((y == 0).sum()),
    },
    "threshold_grid": grid,
    "roc": M["roc_points"],
    "k_sweep": M["k_sweep"],
    "elbow_k": M["elbow_k"],
    "silhouette_k": M["silhouette_k"],
    "cluster_eval": {"kmeans": M["kmeans_eval"], "gmm": M["gmm_eval"]},
    "kmeans_gmm_agreement": M["kmeans_gmm_agreement"],
    "mean_gmm_confidence": M["mean_gmm_confidence"],
    "low_confidence": M["low_confidence_customers"],
    "model_comparison": M["churn_model_comparison"],
    "cv": M["churn_cv"],
    "metrics_tuned": M["churn_metrics_tuned"],
    "segments": M["segment_summary"],
    "segment_order": M["segment_order"],
    "surrogate": {
        "accuracy": M["segment_surrogate"]["accuracy"],
        "macro_precision": M["segment_surrogate"]["macro_precision"],
        "macro_recall": M["segment_surrogate"]["macro_recall"],
        "macro_f1": M["segment_surrogate"]["macro_f1"],
        "kappa": M["segment_surrogate"]["cohen_kappa"],
        "labels": M["segment_surrogate"]["labels"],
        "confusion_matrix": M["segment_surrogate"]["confusion_matrix"],
    },
    "feature_importance": M["feature_importance"],
    "ucg_balance": M["ucg_balance"],
    "cleaning_report": M["cleaning_report"],
    "outlier_caps": M["outlier_caps"],
    "offer_book": {
        seg: {"offer": v[0], "action": v[1], "priority": v[2]}
        for seg, v in campaign.OFFER_BOOK.items()
    },
    "provenance": {
        "synthetic": C.USE_SYNTHETIC,
        "source": (
            "Synthetic subscriber base, schema-compatible with the production feed. "
            "Generated by src/data.py from six latent behavioural populations."
            if C.USE_SYNTHETIC
            else "Production subscriber extract."
        ),
    },
    "samples": json.load(open(C.OUT_DIR / "sample_predictions.json")),
}

with open(C.OUT_DIR / "dashboard_data.json", "w") as f:
    json.dump(payload, f, separators=(",", ":"), default=str)

TOKEN = ">__DATA__</script>"

tpl = (C.ROOT / "dashboard_template.html").read_text()

# Substitute ONLY the placeholder sitting inside the payload <script> tag.
# A naive tpl.replace("__DATA__", data) would also clobber any occurrence of
# the token in the template's own explanatory copy or its guard clause.
n = tpl.count(TOKEN)
if n != 1:
    raise RuntimeError(f"expected exactly 1 payload placeholder, found {n}")

blob = json.dumps(payload, separators=(",", ":"), default=str)
if "</script" in blob.lower():
    raise RuntimeError("payload contains '</script' and would break out of the tag")

html = tpl.replace(TOKEN, ">" + blob + "</script>")
(C.OUT_DIR / "dashboard.html").write_text(html)

print(f"threshold grid rows: {len(grid)}")
print(f"payload size: {(C.OUT_DIR/'dashboard_data.json').stat().st_size/1024:.1f} KB")
print(f"dashboard.html: {(C.OUT_DIR/'dashboard.html').stat().st_size/1024:.1f} KB")
print(f"test set: {len(y):,}  positives={int((y==1).sum()):,}  negatives={int((y==0).sum()):,}")
